services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Demo controllers for testing
  Freema\PerspectiveApiBundle\Dev\Controller\:
    resource: '../Controller'
    tags: ['controller.service_arguments']